### ISSUE TITLE
TypeError when setting background color 

### ISSUE THREAD

**Issue by z0mbieinc** [twilsonco/PyPhotoCollage#6]
I tried setting background color with:
`-b (255, 255, 255)` and `-b [255, 255, 255]`
but I am getting the following error:

```shell
Traceback (most recent call last):
  File "~\PhotoCollage.py", line 656, in <module>
    main()
  File "~\PhotoCollage.py", line 623, in main
    collage = makeCollage(pil_images,
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "~\PhotoCollage.py", line 379, in makeCollage
    img = makeCollage(batch_img_list,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\PhotoCollage.py", line 467, in makeCollage
    background += tuple([255])
TypeError: unsupported operand type(s) for +=: 'generator' and 'tuple'
```

**Comment by nchuecos** [comment]
I had the same issue, opened a pulled request that fixes the issue:
https://github.com/twilsonco/PyPhotoCollage/pull/8

**Comment by twilsonco** [comment]
Thanks you two. PR is merged. Appreciate the feedback and contribution!
